name: "Add PR Comment when there are changes on file list"
description: "Add Pull Request Comment when there are changes on file list"

inputs:
   files:
      description: "Files to check if there is change"
      required: true
   files_ignore:
      description: "Files to ignore when check the PR changes"
      required: true
   pr_message:
      description: "Message to add on PR if there is any change on input files"
      required: true      
   github_token: 
      description: "The github token"
      required: true
   github_event_number:
      description: "PR id"
      required: true
      
runs:
  using: "composite"
  steps:
   - name: Checkout Code
     uses: actions/checkout@v3

   - name: Fetch files changes
     id: changed-files
     uses: tj-actions/changed-files@v19
     with:
       files: |
         ${{ inputs.files }}
       files_ignore: |
         ${{ inputs.files_ignore }}
      
   - name: Add PR Comment if any file on input list was changed
     if: steps.changed-files.outputs.any_modified == 'true'
     uses: actions/github-script@v2
     with:
        github-token: ${{ inputs.github_token }}
        script: |
         github.issues.createComment({
            issue_number: ${{ inputs.github_event_number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{ inputs.pr_message }}
         }) 
